"""pass

Revision ID: 34281b3a50f6
Revises: 40d064bc1a1b
Create Date: 2025-03-06 19:14:30.258969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34281b3a50f6'
down_revision = '40d064bc1a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
